Vagrant.configure("2") do |config|
         config.vm.provider :libvirt do |libvirt|
         libvirt.driver = "kvm"
         libvirt.host = 'localhost'
         libvirt.uri = 'qemu:///system'
         end
config.vm.define "new" do |mkdevbox|
         mkdevbox.vm.box = "mkdevbox"
         mkdevbox.vm.provider :libvirt do |mkdev|
         test.memory = 1024
         test.cpus = 1
         end
         end
end
