Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
         libvirt.driver = "kvm"
         libvirt.host = 'localhost'
         libvirt.uri = 'qemu:///system'
  end

  config.vm.define "workspace" do |workspace|
     workspace.vm.box = "mkdev"
     workspace.vm.provider :libvirt do |workspace|
       workspace.memory = 1024
       workspace.cpus = 1
     end
   
   workspace.vm.provision "shell", path: "puppet_script.sh"

   config.librarian_puppet.puppetfile_dir = "puppet"
   # placeholder_filename defaults to .PLACEHOLDER
   config.librarian_puppet.placeholder_filename = ".MYPLACEHOLDER"
   config.librarian_puppet.use_v1_api  = '1' # Check https://github.com/voxpupuli/librarian-puppet#how-to-use
   config.librarian_puppet.destructive = false # Check https://github.com/voxpupuli/librarian-puppet#how-to-use

    workspace.vm.provision "puppet" do |puppet|

      puppet.environment_path = "puppet/environments"
      puppet.environment = "workspace"
      puppet.options = "--verbose --debug"
      puppet.module_path = "puppet/modules"

    end

end



   config.vm.define "nexus" do |nexus|
     nexus.vm.box = "mkdev"
     nexus.vm.provider :libvirt do |nexus|
       nexus.memory = 1024
       nexus.cpus = 1
   end

   nexus.vm.provision "shell", path: "puppet_script.sh"

   config.librarian_puppet.puppetfile_dir = "puppet"
   # placeholder_filename defaults to .PLACEHOLDER
   config.librarian_puppet.placeholder_filename = ".MYPLACEHOLDER"
   config.librarian_puppet.use_v1_api  = '1' # Check https://github.com/voxpupuli/librarian-puppet#how-to-use
   config.librarian_puppet.destructive = false # Check https://github.com/voxpupuli/librarian-puppet#how-to-use

    nexus.vm.provision "puppet" do |puppet|

      puppet.environment_path = "puppet/environments"
      puppet.environment = "nexus"
      puppet.options = "--verbose --debug"
      puppet.module_path = "puppet/modules"

    end

  end


end


