Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
         libvirt.driver = "kvm"
         libvirt.host = 'localhost'
         libvirt.uri = 'qemu:///system'
  end

  config.vm.define "workspace" do |workspace|
     workspace.vm.box = "mkdev"
     workspace.vm.provider :libvirt do |workspace|
       workspace.memory = 1024
       workspace.cpus = 1
     end
   end

  config.vm.define "nexus" do |nexus|
    nexus.vm.box = "mkdev"
    nexus.vm.provider :libvirt do |nexus|
      nexus.memory = 1024
      nexus.cpus = 1
    end

    nexus.vm.provision "shell", path: "puppet_script.sh"

    nexus.vm.provision "puppet" do |puppet|

      puppet.environment_path = "puppet/environments"
      puppet.environment = "nexus"
      puppet.options = "--verbose --debug"

    end

  end

end


